const ALL_CARDS = [

  {name:"Noobini Pizzanini", rarity:"Commun", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/noobini-santanini-200x300.webp"},
  {name:"Lirilì Larilà", rarity:"Commun", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Liliri_Lalira.webp"},
  {name:"Tim Cheese", rarity:"Commun", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Tim_Cheese-161x300.webp"},
  {name:"Fluriflura", rarity:"Commun", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Fluriflura-215x300.webp"},
  {name:"Talpa Di Fero", rarity:"Commun", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Talpa_Di_Fero-240x300.webp"},
  {name:"Noobini Santanini", rarity:"Commun", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/NoobiniSantanini-204x300.webp"},
  {name:"Svinina Bombardino", rarity:"Commun", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/svinina-bombardino.webp"},
  {name:"Raccooni Jandelini", rarity:"Commun", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Raccooni-197x300.webp"},
  {name:"Pipi Kiwi", rarity:"Commun", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Pipi_Kiwi.webp"},
  {name:"Tartaragno", rarity:"Commun", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/10/Tartaragnoo.webp"},
  {name:"Pipi Corni", rarity:"Commun", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/pipi-corni.webp"},
  {name:"Holy Arepa", rarity:"Commun", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Holy-Arepa-300x169.webp"},



  {name:"Trippi Troppi", rarity:"Rare", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Trippi_Troppi.webp"},
  {name:"Gangster Footera", rarity:"Rare", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/gangster-footera-185x300.webp"},
  {name:"Bandito Bobritto", rarity:"Rare", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/bandito-bobritto-160x300.webp"},
  {name:"Boneca Ambalabu", rarity:"Rare", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Boneca_Ambalabu-226x300.webp"},
  {name:"Cacto Hipopotamo", rarity:"Rare", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Cacto_Hipopotamo1.webp"},
  {name:"Ta Ta Ta Ta Sahur", rarity:"Rare", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/ta-ta-ta-sahur-264x300.webp"},
  {name:"Tric Trac Baraboom", rarity:"Rare", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Tric-Trac-Baraboom-5.webp"},
  {name:"Frogo Elfo", rarity:"Rare", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Frogo_Elfo-181x300.webp"},
  {name:"Pipi Avocado", rarity:"Rare", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/pipi-avocado.webp"},
  {name:"Pengolino Nuvoletto", rarity:"Rare", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Pengolino-Nuvoletto-246x300.webp"},
  {name:"Pinealotto Fruttarino", rarity:"Rare", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Pintealotto.webp"},

  {name:"Cappuccino Assassino", rarity:"Epic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Cappuccino_Assassino-264x300.webp"},
  {name:"Bandito Axolito", rarity:"Epic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Bandito_Axolito1.webp"},
  {name:"Brr Brr Patapim", rarity:"Epic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/brr-brr-patapim-217x300.webp"},
  {name:"Avocadini Antilopini", rarity:"Epic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Avocadini_Antilopini-224x300.webp"},
  {name:"Trulimero Trulicina", rarity:"Epic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/trulimero-trulicina.webp"},
  {name:"Bambini Crostini", rarity:"Epic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/bambini-crostini.webp"},
  {name:"Malame Amarele", rarity:"Epic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/MalameAmarele-200x300.webp"},
  {name:"Bananita Dolphinita", rarity:"Epic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Dolphin_But_Banana-226x300.webp"},
  {name:"Perochello Lemonchello", rarity:"Epic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/perochello-lemonchello.webp"},
  {name:"Brri Brri Bicus Dicus Bombicus", rarity:"Epic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Berry_berry_bicus_dickus.webp"},
  {name:"Avocadini Guffo", rarity:"Epic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/AvocadiniGuffo.webp"},
  {name:"Ti Ti Ti Sahur", rarity:"Epic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/tititi-sahur.webp"},
  {name:"Mangolini Parrocini", rarity:"Epic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/mangolini-parrochini-264x300.webp"},
  {name:"Frogato Pirato", rarity:"Epic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/frogato-pirato.webp"},
  {name:"Gato Celesto", rarity:"Epic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Gato-Celestowebp-286x300.webp"},
  {name:"Salamino Penguino", rarity:"Epic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Salamino-Penguino.webp"},
  {name:"Doi Doi Do", rarity:"Epic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/DoiDoi.webp"},
  {name:"Penguin Tree", rarity:"Epic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/PenguinTree-157x300.webp"},
  {name:"Wombo Rollo", rarity:"Epic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Wombo-200x300.webp"},
  {name:"Penguino Cocosino", rarity:"Epic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Penguino_Cocosino.webp"},
  {name:"Mummio Rappitto", rarity:"Epic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Mummio_Rappitto-215x300.webp"},

  {name:"Chimpanzini Bananini", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/ChimpanziniBananini-262x300.webp"},
  {name:"Tirilikalika Tirilikalako", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/TirilikalikaTirilikalakoTransparent.webp"},
  {name:"Ballerina Cappuccina", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Ballerina_cappucinaaaa212121-261x300.webp"},
  {name:"Burbaloni Loliloli", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/burbaloni-loliloli.webp"},
  {name:"Chef Crabracadabra", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Chef-Crabracadabra.webp"},
  {name:"Lionel Cactuseli", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Lionel-Cactuseli.webp"},
  {name:"Glorbo Fruttodrillo", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/GlorboFruttodrillo.webp"},
  {name:"Quivoli Ameleoni", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Quivioli_Ameleonni.webp"},
  {name:"Blueberrinni Octopusini", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/NewBlueberrinni-1.webp"},
  {name:"Caramello Filtrello", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Caramello_Filtrello2.webp"},
  {name:"Pipi Potato", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/pipi-potato-236x300.webp"},
  {name:"Strawberrelli Flamingelli", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Strawberrelli_Flamingelli.webp"},
  {name:"Cocosini Mama", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Cocosini_Mama-157x300.webp"},
  {name:"Pandaccini Bananini", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Pandaccini_Bananini.webp"},
  {name:"Quackula", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Quackula.webp"},
  {name:"Pi Pi Watermelon", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Pi_Pi_Watermelon.webp"},
  {name:"Signore Carapace", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Teenage_turtle.webp"},
  {name:"Buho del Cielo", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Buho-del-Cielo-140x300.webp"},
  {name:"Sigma Boy", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Sig_ma_Boy-240x300.webp"},
  {name:"Chocco Bunny", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Chocco_Bunny-194x300.webp"},
  {name:"Puffaball", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Puffaball.webp"},
  {name:"Sigma Girl", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/SigmaGirl-216x300.webp"},
  {name:"Sealo Regalo", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Sealo-Regalo-228x300.webp"},
  {name:"Buho de Fuego", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Buhodefuego-244x300.webp"},
  {name:"Seraphino Gruyero", rarity:"Legendary", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Seraphino-Gruyero-300x251.webp"},


  {name:"Frigo Camelo", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/frigo-camelo.webp"},
  {name:"Orangutini Ananassini", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Banana-242x300.webp"},
  {name:"Rhino Toasterino", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/rhino-toasterino-249x300.webp"},
  {name:"Bombardiro Crocodilo", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/A_flying_alligator-1.webp"},
  {name:"Spioniro Golubiro", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/spioniro-golubiro-216x300.webp"},
  {name:"Bombombini Gusini", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/bombombini-gusini.webp"},
  {name:"Zibra Zubra Zibralini", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Zibra_Zubra_Zibralini-151x300.webp"},
  {name:"Tigrilini Watermelini", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Tigrilini_Watermelini1-216x300.webp"},
  {name:"Avocadorilla", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Avocadorilla.webp"},

  {name:"Cavallo Virtuoso", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Cavallo_Virtuoso-221x300.webp"},
  {name:"Gorillo Subwoofero", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/gorillo-subwoofero-248x300.webp"},
  {name:"Gorillo Watermelondrillo", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Gorillo-Watermelondrillo.webp"},
  {name:"Stoppo Luminino", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Stoppo_Luminino-266x300.webp"},
  {name:"Ganganzelli Trulala", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Ganganzelli_Trulala-247x300.webp"},
  {name:"Tob Tobi Tobi", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Tob_Tobi_Tobi.webp"},
  {name:"Lerulerulerule", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Lerulerulerule-256x300.webp"},
  {name:"Te Te Te Sahur", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Te_Te_Te_Sahur.webp"},
  {name:"Rhino Helicopterino", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/rhino-helicopterino.webp"},
  {name:"Magi Ribbitini", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/MagiRibbit.webp"},
  {name:"Tracoducotulu Delapeladustuz", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Tracoducotulu-254x300.webp"},
  {name:"Jingle Jingle Sahur", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/JingleJingleSahur.webp"},
  {name:"Los Noobinis", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Noobinis.webp"},
  {name:"Spongini Quackini", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Spongini-Quackini-179x300.webp"},
  {name:"Cachorrito Melonito", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Watermelon_Doggy-210x300.webp"},
  {name:"Carloo", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Mateo_fish-233x300.webp"},
  {name:"Harpuccino", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Harpuccino-178x300.webp"},
  {name:"Elefanto Frigo", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Elefanto_Frigo_Transparent.webp"},
  {name:"Carrotini Brainini", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/carrotini-brainini.webp"},
  {name:"Centrucci Nuclucci", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Centrucci_Nuclucci-191x300.webp"},
  {name:"Toiletto Focaccino", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Toiletto-236x300.webp"},
  {name:"Jacko Spaventosa", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/jacko-spaventosa-213x300.webp"},
  {name:"Bananito Bandito", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/bananito-bandito-212x300.webp"},
  {name:"Tree Tree Tree Sahur", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/TreeTreeTreeSahur-210x300.webp"},
  {name:"Fizzy Soda", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Fizzy-Soda-195x300.webp"},
  {name:"Berenjello Angello", rarity:"Mythic", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Berenjello-Angello-212x300.webp"},


  {name:"Cocofanto Elefanto", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Cocofanto.webp"},
  {name:"Antonio", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Antonio.webp"},
  {name:"Girafa Celestre", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Girafa-celestre-205x300.webp"},
  {name:"Gattatino Neonino", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Gattatinoneonino.webp"},
  {name:"Gattatino Nyanino", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Gattatin.webp"},
  {name:"Chihuanini Taconini", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/11/Chihuanini-Taconini-218x300.webp"},
  {name:"Matteo", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Matteofr-236x300.webp"},
  {name:"Tralalero Tralala", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/TralaleroTralala.webp"},
  {name:"Los Crocodillitos", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/LosCrocodillitos.webp"},
  {name:"Tigroligre Frutonni", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Tigroligre-264x300.webp"},
  {name:"Odin Din Din Dun", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/odin-din-din-dun.webp"},
  {name:"Money Money Man", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Money_Money_Man-204x300.webp"},
  {name:"Alessio", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/alessio-214x300.webp"},
  {name:"Statutino Libertino", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/StatutinoLibertino.webp"},
  {name:"Tipi Topi Taco", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/11/Tipi_Topi_Taco.webp"},
  {name:"Unclito Samito", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/unclito-samito-215x300.webp"},
  {name:"Tralalita Tralala", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Tralalita.webp"},
  {name:"Tukanno Bananno", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Tukanno_Bananno.webp"},
  {name:"Extinct Ballerina", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/extinct-ballerina.webp"},
  {name:"Vampira Cappucina", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/VampiraCappuccina.webp"},
  {name:"Espresso Signora", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Espresso_Signora-232x300.webp"},
  {name:"Orcalero Orcala", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Orcalero_Orcala.webp"},
  {name:"Jacko Jack Jack", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Jacko_Jack_Jack.webp"},
  {name:"Urubini Flamenguini", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/urubini-flamenguini-181x300.webp"},
  {name:"Trippi Troppi Troppa Trippa", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Trippi_Troppi_Trooppi_TrooaaapppaaHELP_IM_ABOUT_TO_GET_INTO_A_CAR_CRASH.webp"},
  {name:"Capi Taco", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Capi_Taco-239x300.webp"},
  {name:"Divino Platypio", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Divino-Platypio-201x300.webp"},
  {name:"Los Chihuaninis", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Los_Chihuaninis.webp"},
  {name:"Gattito Tacoto", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/11/Gattito-Tacoto.webp"},
  {name:"Las Capuchinas", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Las_Cappuchinas-1.webp"},
  {name:"Bulbito Bandito Traktorito", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/bulbito-bandito-traktorito.webp"},
  {name:"Ballerino Lololo", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Ballerinolololo.webp"},
  {name:"Los Tungtungtungcitos", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/los-tungtungtungcitos.webp"},
  {name:"Ballerina Peppermintina", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Ballerina_Peppermintina-230x300.webp"},
  {name:"Pakrahmatmamat", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Pakrahmatmamat-255x300.webp"},
  {name:"Brr es Teh Patipum", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Brr-es-Teh-Patipum-239x300.webp"},
  {name:"Piccione Macchina", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/piccione-machina-265x300.webp"},
  {name:"Pakrahmatmatina", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Pakrematina.webp"},
  {name:"Los Bombinitos", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/los-bombinitos.webp"},
  {name:"Tractoro Dinosauro", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/TractorDino.webp"},
  {name:"Los Orcalitos", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Los_orcalitos.webp"},
  {name:"Cacasito Satalito", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/cacasito-satalito.webp"},
  {name:"Orcalita Orcala", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/orcalita-orcala.webp"},
  {name:"Corn Corn Corn Sahur", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/CornSahur-158x300.webp"},
  {name:"Mummy Ambalabu", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Mummy_Ambalabu-112x300.webp"},
  {name:"Snailenzo", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Snailenzo.webp"},
  {name:"Squalanana", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Squalanana.webp"},
  {name:"Tartaruga Cisterna", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Tartaruga_Cisternaaaa.webp"},
  {name:"Aquanaut", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Aquanaut-228x300.webp"},
  {name:"Ginger Globo", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Ginger_Globo-211x300.webp"},
  {name:"Yeti Claus", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Yeti_Claus-255x300.webp"},
  {name:"Crabbo Limonetta", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/crabo-limonetta-297x300.webp"},
  {name:"Tootini Shrimpini", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Tootini-Shrimpini-300x252.webp"},
  {name:"Granchiello Spiritell", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Gangster_Crab.webp"},
  {name:"Los Tipi Tacos", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Los_tipi_tacos.webp"},
  {name:"Frio Ninja", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/FrioNinja-238x300.webp"},
  {name:"Buho De Noelo", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Buho-De-Nuelo-300x257.webp"},
  {name:"Boba Panda", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Boba-Panda-203x300.webp"},
  {name:"Piccionetta Macchina", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Piccionetta-Macchina-242x300.webp"},
  {name:"Bambu Bambu Sahur", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Bambu_sahur_full_rost.webp"},
  {name:"Los Gattitos", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Los_Gattitos.webp"},
  {name:"Mastodontico Telepiedone", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Mastodontico-Telepiedone-221x300.webp"},
  {name:"Chrismasmamat", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Chrismasmamat-162x300.webp"},
  {name:"Astrolero Cervalero", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Astrolero-Cervalero-155x300.webp"},
  {name:"Anpali Babel", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/anpali-babel.webp"},
  {name:"Luv Luv Luv", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/02/LuvLuvLuv-1-157x300.webp"},
  {name:"Cappuccino Clownino", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Cappuccinoclown-236x300.webp"},
  {name:"Bombardini Tortinii", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Bombardini_tortilii.webp"},
  {name:"Brasilini Berimbini", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/brasilini-berimbini-200x300.webp"},
  {name:"Patteo", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Patteo-179x300.webp"},
  {name:"Belula Beluga", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Belulaa.webp"},
  {name:"Krupuk Pagi Pagi", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/krapuk-pagi-pagi-239x300.webp"},
  {name:"Skull Skull Skull", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Skully-191x300.webp"},
  {name:"Cocoa Assassino", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Cocoa-Assassino-249x300.webp"},
  {name:"Tentacolo Tecnico", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/tentacolo-tecnico.webp"},
  {name:"Ginger Cisterna", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Ginger_Cisterna-233x300.webp"},
  {name:"Pandanini Frostini", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Pandanini-Frostini-199x300.webp"},
  {name:"Dolphini Jetskini", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Dolphini-Jetskini-261x300.webp"},
  {name:"Pop Pop Sahur", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/PopPopSahur-253x300.webp"},
  {name:"Noo La Polizia", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Nooo_my_polizia.webp"},
  {name:"Karkerheart Luvkur", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/02/Karkerheart-Luvkur-219x300.webp"},
  {name:"Clovkur Kurkur", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Clovkur-Kurkur.webp"},
  {name:"Dumborino Miracello", rarity:"Brainrot God", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Dumborino-Miracello-300x298.webp"},



  {name:"La Vacca Saturno Saturnita", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/La_Vaccca_Saturno_Saturnita.webp"},
  {name:"Bisonte Giuppitere", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Bisonte_Giuppitere_normal.webp"},
  {name:"Sammyni Spyderini", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Sammy_blud.webp"},
  {name:"Blackhole Goat", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Blackhole_goat.webp"},
  {name:"Jackorilla", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Jackorilla-234x300.webp"},
  {name:"Karkerkar Kurkur", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Karkerkar-kurkur-254x300.webp"},
  {name:"Agarrini La Palini", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Agarrini_la_Palini-177x300.webp"},
  {name:"Chachechi", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/chachechi.webp"},
  {name:"Trenostruzzo Turbo 4000", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Trenostruzzo-Turbo-4000-271x300.webp"},
  {name:"Chimpanzini Spiderini", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Chimpanzee_Spider.webp"},
  {name:"Los Matteos", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/LosMatteos.webp"},
  {name:"Los Tortus", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/LosTortuss.webp"},
  {name:"Los Tralaleritos", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/10/Los_Tralaleritos-300x217.webp"},
  {name:"La Cucaracha", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/La_Cucaracha-253x300.webp"},
  {name:"Vulturino Skeletono", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Vulturino.webp"},
  {name:"Boatito Auratito", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Boatito_Auratito-225x300.webp"},
  {name:"Torrtuginni Dragonfrutini", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/tortugini-dragonfrutini-300x289.webp"},
  {name:"Los Spyderinis", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Los_Spyderinis.webp"},
  {name:"Extinct Tralalero", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/extinct-tralalero-300x248.webp"},
  {name:"Fragola La La La", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/fragola-lala.webp"},
  {name:"Zombie Tralala", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/ZombieTralala.webp"},
  {name:"Yess my examine", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Yessmyexamine.webp"},
  {name:"Extinct Matteo", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/extinct-matteo-212x300.webp"},
  {name:"Dul Dul Dul", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Dul_Dul_Dul-215x300.webp"},
  {name:"Guerriro Digitale", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Guerrirodigitale.webp"},
  {name:"Las Tralaleritas", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/LasTralaleritas.webp"},
  {name:"Rocco Disco", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Rocco-Disco-201x300.webp"},
  {name:"La Karkerkar Combinasion", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/La-Karkerkar-Combinasion-227x300.webp"},
  {name:"La Vacca Prese Presente", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/La-Present-Vacca-300x261.webp"},
  {name:"Reindeer Tralala", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Reindeer_Tralala.webp"},
  {name:"Pumpkini Spyderini", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/pumpkini-spyderini.webp"},
  {name:"Los Trios", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Los-Trios-300x165.webp"},
  {name:"Frankentteo", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Frankenmtteo-169x300.webp"},
  {name:"Job Job Job Sahur", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Job-263x300.webp"},
  {name:"Karker Sahur", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Karkar_sahur-252x300.webp"},
  {name:"Las Vaquitas Saturnitas", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/las-vaquitas-saturnitas.webp"},
  {name:"Los Karkeritos", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Loskarkeritos.webp"},
  {name:"Santteo", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Santteo-179x300.webp"},
  {name:"Fishboard", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/02/Fishboard-768x563.webp"},
  {name:"La Vacca Jacko Linterino", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/La-Vacca-Jacko-Linterino.webp"},
  {name:"Triplito Tralaleritos", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Triplito-Tralaleritos.webp"},
  {name:"Paradiso Axolottino", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Paradiso-Axolottino-242x300.webp"},
  {name:"Trickolino", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Trickortreat.webp"},
  {name:"GOAT", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/GOAT.webp"},
  {name:"Giftini Spyderini", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Giftspider.webp"},
  {name:"Love Love Love Sahur", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/02/Love-Love-Love-Sahur.webp"},
  {name:"Graipuss Medussi", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Graipuss.webp"},
  {name:"Perrito Burrito", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/11/Perrito-Burrito.webp"},
  {name:"La Vacca Lepre Lepreino", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/La-Vacca-Lepre-Lepreino-297x300.webp"},
  {name:"1x1x1x1", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/1x1x1x1t.webp"},
  {name:"Los Cucarachas", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Los-Cucarachas.webp"},
  {name:"Please my Present", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/please-my-present-242x300.webp"},
  {name:"Cuadramat and Pakrahmatmamat", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Cuadramat-1.webp"},
  {name:"Bunnyman", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Bunnyman-270x300.webp"},
  {name:"Coffin Tung Tung Tung Sahur", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/coffin-tung-tung.webp"},
  {name:"Tung Tung Tung Sahur", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Tung_Tung_Tung_Sahur-188x300.webp"},
  {name:"Los Jobcitos", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/LosJobcitos.webp"},
  {name:"Nooo My Hotspot", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/NoMyHotspot.webp"},
  {name:"Noo my examine", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Noo_My_Examen.webp"},
  {name:"La Sahur Combinasion", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/la-sahur-combinasion-260x300.webp"},
  {name:"List List List Sahur", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/List_List_List_Sahur-264x300.webp"},
  {name:"Telemorte", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Telemorte-250x300.webp"},
  {name:"To to to Sahur", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/to-to-to-Sahur.webp"},
  {name:"Pirulitoita Bicicleteira", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Pirulitoita-Bicicleteira-223x300.webp"},
  {name:"25", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/25-232x300.webp"},
  {name:"Pot Hotspot", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Pot_Hotspot-144x300.webp"},
  {name:"Santa Hotspot", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Santa-Hotspot.webp"},
  {name:"Horegini Boom", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/horegini-boom.webp"},
  {name:"Pot Pumpkin", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/PotHotpumkin-164x300.webp"},
  {name:"Naughty Naughty", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Sought-the-naught-191x300.webp"},
  {name:"Quesadilla Crocodila", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/11/Quesadilla-Crocodila-294x300.webp"},
  {name:"Cupid Cupid Sahur", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Cupid-Cupid-Sahur-219x300.webp"},
  {name:"Mi Gatito", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/02/Mi-Gatito.webp"},
  {name:"Ho Ho Ho Sahur", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/HoHoHoSahur-222x300.webp"},
  {name:"Cupid Hotspot", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/02/Cupid-Hotspot.webp"},
  {name:"Chicleteira Bicicleteira", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Chicleteira-Bicicleteira-1-236x300.webp"},
  {name:"Brunito Marsito", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Brunito-Marsito-233x300.webp"},
  {name:"Quesadillo Vampiro", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/11/Quesadillo-Vampiro-179x300.webp"},
  {name:"Luck Luck Luck Sahur", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Luck-Luck-Luck-Sahur--300x260.webp"},
  {name:"Chicleteirina Bicicleteirina", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Chicleteirina-Bicicleteirina-200x300.webp"},
  {name:"Burrito Bandito", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/11/Burrito-Bandito-157x300.webp"},
  {name:"Chill Puppy", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Chill-Puppy-265x300.webp"},
  {name:"Bunito Bunito Spinito", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Bunito-Bunito-Spinito-217x300.webp"},
  {name:"Los Quesadillas", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/LosQuesadillas.webp"},
  {name:"Arcadopus", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Arcadopus-247x300.webp"},
  {name:"Noo my candy", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Noo_my_candy_transparent-218x300.webp"},
  {name:"Serafinna Medusella", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Serafinna-Medusella.webp"},
  {name:"La Grande Combinasion", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/la-grande-combinasion-225x300.webp"},
  {name:"Los Nooo My Hotspotsitos", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/LosNooMyHotspotsitos.webp"},
  {name:"Noo my Present", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Noo-my-Present-291x300.webp"},
  {name:"Guest 666", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Guest666t.webp"},
  {name:"Rang Ring Bus", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/RingRangBus2.webp"},
  {name:"Los Mi Gatitos", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/02/Los-Mi-Gatitos-768x483.webp"},
  {name:"Los Chicleteiras", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Los_ditos.webp"},
  {name:"67", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Steal-a-Brainrot-67.webp"},
  {name:"Donkeyturbo Express", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Donkeyturbo-Express-211x300.webp"},
  {name:"Los Burritos", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Los-Burritos.webp"},
  {name:"Los 25", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Los-25.webp"},
  {name:"Tacorillo Crocodillo", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Tacorillo-Crocodrilo-173x300.webp"},
  {name:"Mariachi Corazoni", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/MariachiCora-198x300.webp"},
  {name:"Noo my Heart", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/02/Noo-My-Heart-300x300.webp"},
  {name:"Swag Soda", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Swag_Soda-245x300.webp"},
  {name:"Noo my Gold", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Noo-My-Gold-247x300.webp"},
  {name:"Chimnino", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Chimnino-177x300.webp"},
  {name:"Chicleteira Noelteira", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Noel-259x300.webp"},
  {name:"Los Combinasionas", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/los-combinasionas-300x224.webp"},
  {name:"Fishino Clownino", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Fishino_Clownino-199x300.webp"},
  {name:"Los Sweethearts", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Los-Sweethearts-300x300.webp"},
  {name:"Tacorita Bicicleta", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/11/Tacorita-Bicicleta-282x300.webp"},
  {name:"Spinny Hammy", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Spinny-Hammy-218x300.webp"},
  {name:"Nuclearo Dinossauro", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Nuclearo_Dinosauro.webp"},
  {name:"DJ Panda", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/02/DJ-Panda-201x300.webp"},
  {name:"Las Sis", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Las_Sis.webp"},
  {name:"Chicleteira Cupideira", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/02/Chicleteira-Cupideira-300x282.webp"},
  {name:"Chillin Chili", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Chilin-239x300.webp"},
  {name:"Money Money Reindeer", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Money-Money-Reindeer-237x300.webp"},
  {name:"Chipso and Queso", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Chipsoqueso-265x300.webp"},
  {name:"Los Bros", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/los-bros.webp"},
  {name:"Money Money Puggy", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Money_money_puggy.webp"},
  {name:"Los Planitos", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Los_Planitos.webp"},
  {name:"Snailo Clovero", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Snailo-Clovero-263x300.webp"},
  {name:"Los Mobilis", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Los-Mobilis-225x300.webp"},
  {name:"Celularcini Viciosini", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/celular.webp"},
  {name:"Los 67", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Los-67-brainrot-300x235.webp"},
  {name:"Tuff Toucan", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Tuff-Toucan-243x300.webp"},
  {name:"Mieteteira Bicicleteira", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Mieteteira_Bicicleteira-241x300.webp"},
  {name:"Gobblino Uniciclino", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Gobblino_Uniciclino.webp"},
  {name:"La Spooky Grande", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/02/La-Spooky-Grande-225x300.webp"},
  {name:"Los Jolly Combinasionas", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Los-jolly-Combinasionas-768x596.webp"},
  {name:"Cigno Fulgoro", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Cigno-Fulgoro-271x300.webp"},
  {name:"Los Spooky Combinasionas", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Lospookycombi.webp"},
  {name:"Los Hotspotsitos", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Loshotspotsitos.webp"},
  {name:"Los Candies", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Los-Candies.webp"},
  {name:"Tralaledon", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/tralaledon.webp"},
  {name:"Los Cupids", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Los-Cupids-253x300.webp"},
  {name:"Los Puggies", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Los-Puggies.webp"},
  {name:"W or L", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Win-Or-Lose.webp"},
  {name:"La Extinct Grande", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/La_Extinct_Grande-208x300.webp"},
  {name:"Esok Sekolah", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/EsokSekolah2.webp"},
  {name:"La Jolly Grande", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/La_Chrismas_Grande-172x300.webp"},
  {name:"Los Primos", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Los-Primos.webp"},
  {name:"Bacuru and Egguru", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Bacuru-and-Egguru-768x768.webp"},
  {name:"Eviledon", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Eviledonn.webp"},
  {name:"Los Tacoritas", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/los-tacoritas.webp"},
  {name:"Lovin Rose", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Lovin-Rose-282x300.webp"},
  {name:"Tang Tang Keletang", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/TangTang.webp"},
  {name:"Ketupat Kepat", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/KetupatKepat-255x300.webp"},
  {name:"La Taco Combinasion", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/taco-combinasion-296x300.webp"},
  {name:"Dug Dug Dug", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/DUG_DUG_DUG_BRAINROT.webp"},
  {name:"Tictac Sahur", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/tictac-sahur.webp"},
  {name:"Swaggy Bros", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Swaggy-Bros-300x255.webp"},
  {name:"La Romantic Grande", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/La-Romantic-Grande-286x300.webp"},
  {name:"La Supreme Combinasion", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/SupremeCombinasion-204x300.webp"},
  {name:"Orcaledon", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Orcaledon.webp"},
  {name:"Ketchuru And Musturu", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Ketchuru.webp"},
  {name:"Jolly Jolly Sahur", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Jolly-Jolly-Sahur-207x300.webp"},
  {name:"Gold Gold Gold", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Gold-Gold-Gold.webp"},
  {name:"Nacho Spyder", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Nacho-Spyder-300x276.webp"},
  {name:"Rosetti Tualetti", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/02/Rossetti-Tualetti-300x265.webp"},
  {name:"Garama and Madundung", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Garamadundung.webp"},
  {name:"Cloverat Clapat", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Cloverat-Clapat-281x300.webp"},
  {name:"Spaghetti Tualetti", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/11/Spaghettitualetti-300x258.webp"},
  {name:"Ventoliero Pavonero", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/02/Ventoliero-Pavonero-300x300.webp"},
  {name:"Festive 67", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Festive-67-brainrot-300x228.webp"},
  {name:"Los Spaghettis", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Los-Spaghettis-768x571.webp"},
  {name:"Sammyni Fattini", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/02/Sammyni-Fattini-206x300.webp"},
  {name:"Hokka Horloge", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Hokka-Horloge-e1766159114487-220x300.webp"},
  {name:"Ginger Gerat", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Ginger-Gerat-210x300.webp"},
  {name:"La Ginger Sekolah", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/La_ginger_Sekolah-1-222x300.webp"},
  {name:"Spooky and Pumpky", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/10/Spookypumpky.webp"},
  {name:"Lavadorito Spinito", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Lavadorito_Spinito-203x300.webp"},
  {name:"La Food Combinasion", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/02/La-Food-Combinasion-192x300.webp"},
  {name:"Fragrama and Chocrama", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Fragrama.webp"},
  {name:"La Casa Boo", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Casa_Booo.webp"},
  {name:"Los Sekolahs", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/02/Los-Sekolahs-300x211.webp"},
  {name:"Foxini Lanternini", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Foxini-Lanternini-273x300.webp"},
  {name:"La Secret Combinasion", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Lasecretcombinasion-226x300.webp"},
  {name:"Fortunu and Cashuru", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Fortunu-and-Cashuru-300x240.webp"},
  {name:"Los Amigos", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/02/Los-Amigos-768x576.webp"},
  {name:"Reinito Sleighito", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Reinito-Sleighito-234x300.webp"},
  {name:"Ketupat Bros", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Ketupat-Bros-300x286.webp"},
  {name:"Burguro And Fryuro", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Burguro-And-Fryuro-1-258x300.webp"},
  {name:"Cooki and Milki", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/Cooki_and_milki-1.webp"},
  {name:"Capitano Moby", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/capitano-moby-300x284.webp"},
  {name:"Rosey and Teddy", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/02/Rosey-and-Teddy-300x282.webp"},
  {name:"Popcuru and Fizzuru", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/02/Popuru-and-Fizzuru-240x300.webp"},
  {name:"Cerberus", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Cerberus-1-292x300.webp"},
  {name:"Celestial Pegasus", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/02/Celestial-Pegasus-e1773659768625-300x252.webp"},
  {name:"Love Love Bear", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Love-Love-Bear-248x300.webp"},
  {name:"Dragon Cannelloni", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/dragon-canneloni-300x256.webp"},
  {name:"Dragon Gingerini", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2025/12/DragonGingerini-300x284.webp"},
  {name:"Hydra Dragon Cannelloni", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/01/Hydra-Dragon-Cannelloni-261x300.webp"},
  {name:"Griffin", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Griffin-e1773654223940-768x534.webp"},

  {name:"La Lucky Grande", rarity:"Secret", image:"https://static.wikia.nocookie.net/stealabr/images/5/55/La_Lucky_Grande.png/revision/latest?cb=20260323180752"},
  {name:"La Easter Grande", rarity:"Secret", image:"https://static.wikia.nocookie.net/stealabr/images/2/2e/Easter_La_Grande.png/revision/latest?cb=20260401014142"},
  {name:"Boppin Bunny", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Boppin-Bunny-300x300.webp"},
  {name:"Bunny and Eggy", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Bunny-and-Eggy-300x300.webp"},
  {name:"Buntteo", rarity:"Secret", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Buntteo-300x300.webp"},



  { name:"Skibidi Toilet", rarity:"OG", image:"https://cdn.phototourl.com/uploads/2026-03-14-3be000d4-c396-4f70-9827-7b9f3208525e.png" },
  { name:"Headless Horseman", rarity:"OG", image:"https://cdn.phototourl.com/uploads/2026-03-14-afc3dd97-67c3-4c8b-94be-e3909d345d21.png" },
  { name:"John Pork", rarity:"OG", image:"https://cdn.phototourl.com/uploads/2026-03-14-e72fbeb0-d333-45cc-afd2-f501c066d2f8.png" },
  { name:"Meowl", rarity:"OG", image:"https://cdn.phototourl.com/uploads/2026-03-14-6acb0782-4a61-4b79-b994-e0c5717f6672.png" },
  { name:"Smurf Cat", rarity:"OG", image:"https://cdn.phototourl.com/uploads/2026-03-14-22b121bc-4380-4104-aff6-a2adf5f7bca5.png" },
  { name:"Strawberry Elephant", rarity:"OG", image:"https://cdn.phototourl.com/uploads/2026-03-14-86e303da-a89b-41d3-9902-35c2e8fea136.png" },



  {name:"Mythic Lucky Block", rarity:"Mythic Lucky Block", image:"https://cdn.phototourl.com/free/2026-04-01-2edf73c6-3e2e-4b33-ae53-6c1c44fcf906.png"},
  {name:"Brainrot God Lucky Block", rarity:"Brainrot God Lucky Block", image:"https://cdn.phototourl.com/free/2026-04-01-1b915287-bc30-41b2-a3b7-18430ab224f5.png"},
  {name:"Secret Lucky Block", rarity:"Secret Lucky Block", image:"https://cdn.phototourl.com/free/2026-04-01-a0056889-8807-4e3b-aacf-e0b0c6d3f416.jpg"},
  {name:"Admin Lucky Block", rarity:"Admin Lucky Block", image:"https://cdn.phototourl.com/free/2026-04-01-c8d900b7-abd6-4fac-bb8a-d13b20ce6016.jpg"},


  {name:"Noo my Eggs", rarity:"Exclu Season 1", image:"https://www.eldorado.gg/blog/wp-content/uploads/2026/03/Noo-my-Eggs-300x300.webp"},


];
